FROM hackinglab/alpine-base:3.2

ENV HL_USER_USERNAME=root
ENV HL_USER_PASSWORD=compass
ENV HL_ROOT_PASSWORD=test..123

# Add the files

ADD root /

RUN chmod -R 777 /bin

RUN adduser -m hacker

RUN passwd hacker test..123

ENV SIAB_USERCSS="Normal:+/etc/shellinabox/options-enabled/00_White-On-Black.css,Reverse:-/etc/shellinabox/options-enabled/00+Black-on-White.css;Colors:+/etc/shellinabox/options-enabled/01+Color-Terminal.css,Monochrome:-/etc/shellinabox/options-enabled/01_Monochrome.css" \
  SIAB_PORT=4200 \
  SIAB_ADDUSER=true \
  SIAB_USER=hacker \
  SIAB_USERID=1337 \
  SIAB_GROUP=hacker \
  SIAB_GROUPID=1337 \
  SIAB_PASSWORD=compass \
  SIAB_SHELL=/bin/bash \
  SIAB_HOME=/home/hacker \
  SIAB_SUDO=false \
  SIAB_SSL=true \
  SIAB_SERVICE=/:LOGIN \
  SIAB_PKGS=none \
  SIAB_SCRIPT=none

# ENV SIAB_USERCSS="Normal:+/etc/shellinabox/options-enabled/00+Black-on-White.css,Reverse:-/etc/shellinabox/options-enabled/00_White-On-Black.css;Colors:+/etc/shellinabox/options-enabled/01+Color-Terminal.css,Monochrome:-/etc/shellinabox/options-enabled/01_Monochrome.css"

RUN apk add --update bash openssl curl sudo && \
	rm -rf /var/cache/apk/* && \
	adduser -D -H -h /home/shellinabox shellinabox && \
	mkdir /var/lib/shellinabox && \
	chmod +s /bin/su
	
WORKDIR /home/hacker

RUN mkdir -p Dessert/Kekse Dessert/Kuchen Dessert/Torten Dessert/Waffeln

RUN touch Dessert/Kekse/Mandelkekse.txt
RUN touch Dessert/Kuchen/Marmorkuchen.txt
RUN touch Dessert/Torten/Sahnetorte.txt
RUN touch Dessert/Waffeln/Honigwaffeln.txt
RUN touch Dessert/Waffeln/Zuckerwaffeln.txt
	 
#COPY ./files ./hacker

#RUN chown -R hacker /home/hacker

EXPOSE 4200